*PROBLEM 7;
data _null_;
    targetPrime = 10001;
    primeCount = 0;
    x = 1;
    do while (primeCount < targetPrime);
        x + 1;
        prime = 'T';
        do i=2 to x-1;
            if mod(x,i) = 0 then do;
                prime = 'F';
                leave;
            end;
        end;
        if prime = 'T' then do;
            primeCount + 1;
        end;
    end;
    put x=;
run;